version: '3'
services:
  webapp:
    build: .
    env_file:
      - ./environments/db.env
    volumes:
      - .:/output_reading_docker
    ports:
      - 3000:3000
    depends_on:
      - chrome
      - db
    tty: true
    command: bundle exec puma -C config/puma.rb

  chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none
    ports:
      - 4444:4444

  db:
    image: mysql
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d

  nginx:
    build: containers/nginx
    volumes:
      - public-data:/output_reading_docker/public
      - tmp-data:/output_reading_docker/tmp
    ports:
      - 80:80
    depends_on:
      - webapp

volumes:
  public-data:
  tmp-data:
  db-data:
