version: '3.1'
services:
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  webapp:
    build: .
    env_file:
      - ./environments/db.env
    volumes:
      - .:/output_reading_docker
      - public-data:/output_reading_docker/public
      - tmp-data:/output_reading_docker/tmp
      - log-data:/output_reading_docker/log
    depends_on:
      - db
    tty: true
    command: rails s
    # # secretsはデプロイ時のみコメントアウト
    # secrets:
    #   - ec2_rsa
    #   - git_rsa

  nginx:
    build: containers/nginx
    volumes:
      - public-data:/output_reading_docker/public
      - tmp-data:/output_reading_docker/tmp
    ports:
      - 80:80
    depends_on:
      - webapp

  chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none
    ports:
      - 4444:4444
    depends_on:
      - nginx

# # secretsはデプロイ時のみコメントアウト
# secrets:
#   ec2_rsa:
#     file: ${OUTPUT_READING_KEY}
#   git_rsa:
#     file: ${GIT_KEY}

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
