default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: output_reading
  pool: 5
  username: root
  password: JN7+GT*a
  host: localhost

development:
  <<: *default
  database: output_reading_devlopment

test:
  <<: *default
  database: output_reading_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
