default: &default
  adapter: mysql2
  encoding: utf8mb4
  timeout: 5000
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: output_reading_development

test:
  <<: *default
  database: output_reading_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>
  username: <%= Rails.application.credentials.dig(:db, :user) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
