default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: output_reading
  pool: 5
  username: root
  password: JN7+GT*a
  host: localhost

development:
  <<: *default
  database: output_reading_devlopment

test:
  <<: *default
  database: output_reading_test

production:
  <<: *default
  database: output_reading_production
  username: admin
  password: Sd3mnju+
  socket: /var/lib/mysql/mysql.sock
  host: output-reading-mysql.cymfu1ihmhjm.ap-northeast-1.rds.amazonaws.com
